name: Scrape Insider Trades

on:
  schedule:
    # Every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1. Check out THIS private repo (contains scraper/)
      - name: Checkout backend repo
        uses: actions/checkout@v4

      # 2. Check out the PUBLIC repo so we can read + write data/
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: shaheedhamid/insider-radar
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          path: public-repo

      # 3. Copy existing data files into the workspace root so the scraper
      #    finds them at the path it expects (../data relative to scraper/)
      - name: Copy existing data into workspace
        run: |
          mkdir -p data
          cp -r public-repo/data/. data/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scraper/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r scraper/requirements.txt

      - name: Run scraper
        run: python scraper/scrape.py

      # 4. Copy updated data/ back into the public repo checkout, then push
      - name: Push updated data to public repo
        run: |
          cp -r data/. public-repo/data/
          cd public-repo
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add data/latest.json data/history.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update insider trade data [$(date -u +'%Y-%m-%d %H:%M UTC')]"
            git push origin HEAD
          fi
